Fix TypeError in celery task tests when redis is unavailable
```
  File "/code/flask_restx_patched/namespace.py", line 145, in dump_wrapper
    response = func(*args, **kwargs)
  File "/code/app/modules/asset_groups/resources.py", line 100, in post
    asset_group = AssetGroup.create_from_metadata(metadata)
  File "/code/app/modules/asset_groups/models.py", line 939, in create_from_metadata
    added = asset_group.import_tus_files(
  File "/code/app/modules/asset_groups/models.py", line 1017, in import_tus_files
    git_push.delay(str(self.guid))
  File "/code/tests/conftest.py", line 117, in <lambda>
    lambda *args, **kwargs: getattr(tasks, func)(*args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/code/app/__init__.py", line 169, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/code/app/modules/asset_groups/tasks.py", line 83, in sage_detection
    import traceback; traceback.print_stack()
```

```
args = ('6d8cf1e0-9eb8-4508-9102-2d935013ed15',), kwargs = {}

    @wraps(task.run)
    def run(*args, **kwargs):
        try:
>           return task._orig_run(*args, **kwargs)
E           TypeError: sage_detection() missing 1 required positional argument: 'model'
```

The code for patching the tasks functions `.delay()` is incorrect because
"func" is always set to be "sage_detection" (the last item in the loop).

```
 for func in (
     'delete_remote',
     'ensure_remote',
     'git_push',
     'sage_detection',
 ):
     tasks_patch.append(
         mock.patch.object(
             getattr(tasks, func),
             'delay',
-            lambda *args, **kwargs: getattr(tasks, func)(*args, **kwargs),
+            getattr(tasks, func),
         ),
     )
```