Fix error handling code in permission_required decorator
An exception doesn't always have the attribute `code` and this happens
sometimes:

```
    @wraps(func)
    def wrapper(*args, **kwargs):
        with permission(**kwargs_on_request(kwargs)):
            try:
                return func(*args, **kwargs)
            except Exception as ex:
                import app.extensions.logging as AuditLog  # NOQA

>               if 400 > ex.code > 409:
E               AttributeError: 'BuildError' object has no attribute 'code'

flask_restx_patched/namespace.py:402: AttributeError
```

causing us to not be able to see the actual error.

Adding `hasattr(ex, 'code')` fixes the problem.