Catch RuntimeError in check jobs task
We have a periodic task that checks all the asset group sighting jobs sent to
acm.  There's a runtime error because RestManager tries to access the
current request `flask.request` in order to get some header values:

```
[2021-09-07 14:41:16,026: ERROR/ForkPoolWorker-7] Task app.modules.job_control.tasks.check_jobs[ca9c3c27-2faa-4669-a7f8-159b8d8231fd] raised unexpected: RuntimeError('Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request.  Consult the documentation on testing for\ninformation about how to avoid this problem.')                                                Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/app/__init__.py", line 167, in __call__
    return self.run(*args, **kwargs)
  File "/code/app/modules/job_control/tasks.py", line 17, in check_jobs
    JobControl.check_jobs()                                                                                                                          File "/code/app/modules/job_control/models.py", line 18, in check_jobs
    AssetGroupSighting.check_jobs()                                                                                                                  File "/code/app/modules/asset_groups/models.py", line 285, in check_jobs
    asset_group_sighting.check_all_job_status()
  File "/code/app/modules/asset_groups/models.py", line 292, in check_all_job_status
    current_app.acm.request_passthrough_result(
  File "/code/app/extensions/acm/__init__.py", line 125, in request_passthrough_result
    response, response_data, result = self.request_passthrough_parsed(
  File "/code/app/extensions/acm/__init__.py", line 72, in request_passthrough_parsed
    response = self.request_passthrough(tag, method, passthrough_kwargs, args, target)
  File "/code/app/extensions/restManager/RestManager.py", line 368, in request_passthrough
    header_value = request.headers.get(header_key, None)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.9/site-packages/flask/globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.
```

Catch this error and set the header values to none and continue with the
code.