Downgrade itsdangerous<2.1.0 in app/requirements.txt
Flask is importing `itsdangerous.json` which has been removed in 2.1.0. The
documentation said to use the standard library instead.

Error when generating model graph:

```
Traceback (most recent call last):
  File "/home/runner/work/houston/houston/./scripts/docs/generate_models_graph.py", line 34, in <module>
    for model in get_models():
  File "/home/runner/work/houston/houston/./scripts/docs/generate_models_graph.py", line 13, in get_models
    config = get_preliminary_config()
  File "/home/runner/work/houston/houston/config/__init__.py", line 96, in get_preliminary_config
    config_cls = import_class(CONFIG_CLS_MAPPER[ctx][env])
  File "/home/runner/work/houston/houston/config/utils.py", line 18, in import_class
    module = importlib.import_module(path)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/work/houston/houston/config/codex.py", line 5, in <module>
    from .base import (
  File "/home/runner/work/houston/houston/config/base.py", line 8, in <module>
    import flask
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/itsdangerous/__init__.py)
```