Add migration to add test to submissionmajortype enum
After running `invoke app.db.upgrade --no-backup` with a postgresql
database, some tests failed because they use "test" in
"submission.major_type" and that is considered invalid:

```
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input value for enum submissionmajortype: "test"
LINE 1: ...mp, 'd12f3cea-620d-41ab-a009-d7a84ef42be1'::uuid, 'test', NU...
                                                             ^
[SQL: INSERT INTO submission (created, updated, viewed, guid, major_type, commit, commit_mime_whitelist_guid, commit_houston_api_version, description, owner_guid) VALUES (%(created)s, %(updated)s, %(viewed)s, %(guid)s, %(major_type)s, %(commit)s, %(commit_mime_whitelist_guid)s, %(commit_houston_api_version)s, %(description)s, %(owner_guid)s)]
[parameters: {'created': datetime.datetime(2021, 2, 16, 22, 45, 23, 567779), 'updated': datetime.datetime(2021, 2, 16, 22, 45, 23, 567799), 'viewed': datetime.datetime(2021, 2, 16, 22, 45, 23, 567807), 'guid': UUID('d12f3cea-620d-41ab-a009-d7a84ef42be1'), 'major_type': 'test', 'commit': None, 'commit_mime_whitelist_guid': None, 'commit_houston_api_version': None, 'description': 'This is a test submission, please ignore', 'owner_guid': UUID('1c14b1c9-64e6-4f42-9fe3-b13f45806271')}]
```

It turns out in the database "test" is in the submissionmajortype enum:

```
wildbook=# select t.typname, e.enumlabel from pg_type t join pg_enum e on t.oid = e.enumtypid join pg_catalog.pg_namespace n on n.oid = t.typnamespace where t.typname = 'submissionmajortype';
       typname       | enumlabel
---------------------+------------
 submissionmajortype | filesystem
 submissionmajortype | archive
 submissionmajortype | service
 submissionmajortype | unknown
 submissionmajortype | error
 submissionmajortype | reject
(6 rows)
```

In migration f4f2436d30f2, the submissionmajortype was defined
for the first time and didn't include "test".

Then in migration a042326c4b51, the submissionmajortype enum is
changed to include "test" but it was ignored and
submissionmajortype still doesn't include "test".

So this migration adds "test" to "submissionmajortype".