Fix SiteSetting models read edm config tests
If we start with no data in the site, these tests fail:

```
tests/modules/site_settings/test_models.py::test_read_edm_configuration[None] FAILED                                                        [ 50%]
tests/modules/site_settings/test_models.py::test_get_value[None] FAILED                                                                     [100%]

==================================================================== FAILURES =====================================================================
________________________________________________________ test_read_edm_configuration[None] ________________________________________________________

    @pytest.mark.skipif(extension_unavailable('edm'), reason='EDM extension disabled')
    def test_read_edm_configuration():
        val = SiteSetting.get_edm_configuration('site.name')
>       assert isinstance(val, str)
E       assert False
E        +  where False = isinstance(None, str)

tests/modules/site_settings/test_models.py:74: AssertionError

______________________________________________________________ test_get_value[None] _______________________________________________________________

db = <SQLAlchemy engine=postgresql://houston:***@db/houston_test>

    def test_get_value(db):
        # this should grab from edm and return a string
        val = SiteSetting.get_value('site.name')
        if is_extension_enabled('edm'):
>           assert isinstance(val, str)
E           assert False
E            +  where False = isinstance(None, str)

tests/modules/site_settings/test_models.py:52: AssertionError
```

This is because `site.name` and `site.species` are not set in the edm so
`None` is returned.

These tests have been working because either the edm database is already
populated or other tests have created these values.