Fix attribute error deleting gitlab projects
```
Traceback (most recent call last):
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/gitlab/exceptions.py", line 287, in wrapped_f
    return f(*args, **kwargs)
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/gitlab/mixins.py", line 483, in delete
    self.gitlab.http_delete(path, **kwargs)
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/gitlab/client.py", line 788, in http_delete
    return self.http_request("delete", path, **kwargs)
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/gitlab/client.py", line 584, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Project Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/houston/houston/app/extensions/asset_group/__init__.py", line 331, in delete_remote_project
    self.gl.projects.delete(project.id)
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/gitlab/exceptions.py", line 289, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabDeleteError: 404: 404 Project Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/runner/work/houston/houston/virtualenv/houston3.7/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/runner/work/houston/houston/tasks/app/_utils.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/houston/houston/tasks/app/consistency.py", line 143, in cleanup_gitlab
    success = current_app.agm.delete_remote_project(project)
  File "/home/runner/work/houston/houston/app/extensions/asset_group/__init__.py", line 333, in delete_remote_project
    except git_remote.GitRemote.GitRemoteDeleteError:
AttributeError: type object 'GitRemote' has no attribute 'GitRemoteDeleteError'
```