Fix oauth user creation code KeyError
Instead of modifying the `oauth_user` dict in the app config, copy it first so
in case something fails, we won't lose "client_id".

```
2021-09-30 06:49:29,289 [INFO] [werkzeug] 127.0.0.1 - - [30/Sep/2021 06:49:29] "GET /api/v1/site-info/heartbeat HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/code/app/__init__.py", line 70, in _ensure_oauth_user
    client_id = oauth_user.pop('client_id')
KeyError: 'client_id'
```

Also catch extra sqlalchemy.exc.ProgrammingError which is the postgresql error
when the table doesn't exist.