Set viewpoint to be "unknown" if viewpoint is None from sage
Sage currently returns a null viewpoint with the zebra image and it
causes an error when sage calls back:

```
2021-10-21 10:10:36,097 [AUDIT] [app.modules.asset_groups.models] Other of AssetGroupSighting abeb700f-22e3-4f94-81e1-9b6bb9c26f2d Received Sage detection response executed by user :1fb6caa6-0a1f-4621-984d-e1a46891592b oauth-user@wildme.org
2021-10-21 10:10:36,108 [AUDIT] [app.modules.asset_groups.models] Failed: Need a viewpoint "None" and a class "zebra_plains" in each of the results 400 executed by user :1fb6caa6-0a1f-4621-984d-e1a46891592b oauth-user@wildme.org
2021-10-21 10:10:36,110 [ERROR] [app.modules.asset_groups.resources] sage_detected error: b'{"jobid": "30528625-2120-44e2-8c5c-47e58e8d1d83", "status": "completed", "json_result": {"image_uuid_list": [{"__UUID__": "90917c9d-6e50-3b28-7396-c08f77f0c7eb"}], "results_list": [[{"id": 1, "uuid": {"__UUID__": "34aeab15-149a-4796-ad25-0cdae146ad50"}, "xtl": 178, "ytl": 72, "left": 178, "top": 72, "width": 604, "height": 534, "theta": 0.0, "confidence": 0.9185, "class": "zebra_plains", "species": "zebra_plains", "viewpoint": null, "quality": null, "multiple": false, "interest": false}]], "score_list": [0.0], "has_assignments": false}}'
Traceback (most recent call last):
  File "/code/app/modules/asset_groups/resources.py", line 526, in post
    asset_group_sighting.detected(job_guid, json.loads(request.data))
  File "/code/app/modules/asset_groups/models.py", line 484, in detected
    raise HoustonException(
app.utils.HoustonException: Need a viewpoint "None" and a class "zebra_plains" in each of the results
2021-10-21 10:10:36,117 [AUDIT] [app.extensions.logging] 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. executed by user :1fb6caa6-0a1f-4621-984d-e1a46891592b oauth-user@wildme.org
2021-10-21 10:10:36,120 [INFO] [werkzeug] 172.21.0.3 - - [21/Oct/2021 10:10:36] "POST /api/v1/asset_groups/sighting/abeb700f-22e3-4f94-81e1-9b6bb9c26f2d/sage_detected/30528625-2120-44e2-8c5c-47e58e8d1d83 HTTP/1.1" 400 -
```