Change log.error to log.exception so traceback is shown
The difference between `log.error` and `log.exception` is that traceback
is not shown so it's harder to debug:

```
2021-09-07 09:47:32,976 [ERROR] [app.modules.asset_groups.models] create_from_tus() had problems with import_tus_files(); deleting from db and fs <AssetGroup(guid=c2ddfc7f-9738-4624-837c-fa111eb37ba0, )>
2021-09-07 09:47:32,990 [AUDIT] [app.extensions.logging] 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. executed by user :1fe85998-1a3e-492c-bf0c-10a62e6e4e52 root@example.org
```

vs

```
2021-09-07 10:05:50,285 [ERROR] [app.modules.asset_groups.models] create_from_tus() had problems with import_tus_files(); deleting from db and fs <AssetGroup(guid=ecb3450e-80cc-44e3-9205-f5c352004d7f, )>
Traceback (most recent call last):
  File "/code/app/modules/asset_groups/models.py", line 887, in create_from_metadata
    added = asset_group.import_tus_files(
  File "/code/app/modules/asset_groups/models.py", line 957, in import_tus_files
    os.rename(path, os.path.join(asset_group_path, name))
PermissionError: [Errno 13] Permission denied: '/data/var/uploads/trans-9a2185f9-5bf5-487e-a19c-0a4baed43b1e/zebra.jpg' -> '/data/var/asset_group/ecb3450e-80cc-44e3-9205-f5c352004d7f/_asset_group/zebra.jpg'
2021-09-07 10:05:50,483 [AUDIT] [app.extensions.logging] 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. executed by user :1fe85998-1a3e-492c-bf0c-10a62e6e4e52 root@example.org
```