Fix GitRemoteLocal projects.list() without search term
When running `invoke app.integrations.check` with GitRemoteLocal:

```
root@a89ba8638d3b:/code# GITLAB_REMOTE_URI=/data/var/git_remote invoke app.integrations.check
2021-04-30 17:31:09,507 [INFO] [app] Using app.config 'docker_local_config.LocalConfig'
⭐ db (postgresql://houston:development@db/houston)
2021-04-30 17:31:10,060 [INFO] [app.extensions.asset_group] Logging into Asset Group GitLab...
2021-04-30 17:31:10,061 [INFO] [app.extensions.asset_group]      URI: '/data/var/git_remote'
2021-04-30 17:31:10,061 [INFO] [app.extensions.asset_group]      NS : 'TEST'
2021-04-30 17:31:10,062 [INFO] [app.extensions.asset_group] Logged in: <app.extensions.git_remote.GitRemoteLocal object at 0x7ff54c25f520>
2021-04-30 17:31:10,062 [INFO] [app.extensions.asset_group] Using namespace: LocalNamespace(id='TEST', name='TEST')
2021-04-30 17:31:10,062 [ERROR] [tasks.app.integrations]
Traceback (most recent call last):
  File "/code/tasks/app/integrations.py", line 38, in check_gitlab
    app.agm.gl.projects.list()
TypeError: list() missing 1 required positional argument: 'search'
❌ gitlab
```

Return all projects when `projects.list()` is called without a search term