Skip alembic 1.7.0 to fix sqlite3 migration error
On github, after alembic upgraded from 1.6.5 to 1.7.0, during the "Check
DB migrations (sqlite)" step:

```
2021-08-30 18:46:30,567 [INFO] [alembic.runtime.migration] Running upgrade 13e7f8e7bcf8 -> 5c2ffe7143c9, empty message
2021-08-30 18:46:30,574 [CRITICAL] [tasks.app.db] Database upgrade failed
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.9/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/code/tasks/app/_utils.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/code/tasks/app/db.py", line 236, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 104, in <module>
    run_migrations_online()
  File "migrations/env.py", line 96, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 612, in run_migrations
    step.migration_fn(**kw)
  File "/code/migrations/versions/5c2ffe7143c9_.py", line 31, in upgrade
    batch_op.create_foreign_key(batch_op.f('fk_asset_group_submitter_guid_user'), 'user', ['submitter_guid'], ['guid'])
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/base.py", line 369, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/batch.py", line 107, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/sqlite.py", line 69, in add_constraint
    raise NotImplementedError(
NotImplementedError: No support for ALTER of constraints in SQLite dialectPlease refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
```

This might be a temporary regression so just skip 1.7.0 for now...