Improve logging in sage detection callback handler
Instead of just failing with 400 with no error messages, now we get:

```
2021-10-13 21:59:46,474 [AUDIT] [app.modules.asset_groups.models] Other of AssetGroupSighting 2bc1dcb3-72af-4fe8-a776-c0702098b4e3 Received Sage detection response executed by user :1969bb81-65fe-46d5-ab9f-81893f56c970 oauth-user@wildme.org
2021-10-13 21:59:46,483 [AUDIT] [app.modules.asset_groups.models] Failed: Need a viewpoint "None" and a class "zebra_plains" in each of the results 400 executed by user :1969bb81-65fe-46d5-ab9f-81893f56c970 oauth-user@wildme.org
2021-10-13 21:59:46,485 [ERROR] [app.modules.asset_groups.resources] sage_detected error: b'{"jobid": "d00d5808-a17f-46d9-bd74-9d0d7f9bb024", "status": "completed", "json_result": {"image_uuid_list": [{"__UUID__": "90917c9d-6e50-3b28-7396-c08f77f0c7eb"}], "results_list": [[{"id": 1, "uuid": {"__UUID__": "a1d1aa06-c229-44a2-b51f-db1de4f422f8"}, "xtl": 178, "ytl": 72, "left": 178, "top": 72, "width": 604, "height": 534, "theta": 0.0, "confidence": 0.9185, "class": "zebra_plains", "species": "zebra_plains", "viewpoint": null, "quality": null, "multiple": false, "interest": false}]], "score_list": [0.0], "has_assignments": false}}'
Traceback (most recent call last):
  File "/code/app/modules/asset_groups/resources.py", line 526, in post
    asset_group_sighting.detected(job_guid, json.loads(request.data))
  File "/code/app/modules/asset_groups/models.py", line 484, in detected
    raise HoustonException(
app.utils.HoustonException: Need a viewpoint "None" and a class "zebra_plains" in each of the results
2021-10-13 21:59:46,490 [AUDIT] [app.extensions.logging] 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. executed by user :1969bb81-65fe-46d5-ab9f-81893f56c970 oauth-user@wildme.org
2021-10-13 21:59:46,493 [INFO] [werkzeug] 172.21.0.12 - - [13/Oct/2021 21:59:46] "POST /api/v1/asset_groups/sighting/2bc1dcb3-72af-4fe8-a776-c0702098b4e3/sage_detected/d00d5808-a17f-46d9-bd74-9d0d7f9bb024 HTTP/1.1" 400 -
```