Fix tus _parse_metadata when Upload-Metadata is empty
When http header `Upload-Metadata` is not sent, `upload_metadata` is None but
the code still tries to treat it as a string and `.split(',')` fails:

```
self = <app.extensions.tus.flask_tus_cont.TusManager object at 0x7fdd4fbe4be0>

    def _parse_metadata(self):
        metadata = {}
        upload_metadata = request.headers.get('Upload-Metadata')
>       for kv in request.headers.get('Upload-Metadata', None).split(','):

E       AttributeError: 'NoneType' object has no attribute 'split'

app/extensions/tus/flask_tus_cont.py:120: AttributeError
```