Fix DetachedInstanceError in Sighting.check_jobs
DetachedInstanceError happens when you use an object from before
`db.session.commit()` instead of fetching it again from the database
(from what I read online).  For example,

```
with db.session.begin():
    db.session.merge(self)
print(self.guid)  # <- DetachedInstanceError
```

The way I'm trying to fix it is by doing:

```
sighting_guid = str(self.guid)
with db.session.begin():
    db.session.merge(self)
print(sighting_guid)  # or
self = Sighting.query.get(sighting_guid)
```

```
...
    Sighting.check_jobs()
  File "/code/app/modules/sightings/models.py", line 374, in check_jobs
    sighting.check_all_job_status(all_scheduled)
  File "/code/app/modules/sightings/models.py", line 386, in check_all_job_status
    self.ia_pipeline(background=False)
  File "/code/app/modules/sightings/models.py", line 1152, in ia_pipeline
    num_jobs_sent = self.send_annotation_for_identification(
  File "/code/app/modules/sightings/models.py", line 1190, in send_annotation_for_identification
    if self.send_annotation_for_identification_specific(
  File "/code/app/modules/sightings/models.py", line 1263, in send_annotation_for_identification_specific
    self._update_job_config(config_id, algorithm_id, annotation_guid, restart)
  File "/code/app/modules/sightings/models.py", line 1291, in _update_job_config
    self.job_configs = self.job_configs
...
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 942, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Sighting at 0x7f155414d280> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)
```