Fix app.db.current for alembic 1.5.0+
When running `invoke app.db.current` with alembic 1.5.4:

```
2021-02-17 21:26:37,933 [INFO] [app] Using app.config 'local_config.LocalConfig'
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/code/tasks/app/_utils.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/code/tasks/app/db.py", line 341, in current
    command.current(config, verbose=verbose, head_only=head_only)
TypeError: current() got an unexpected keyword argument 'head_only'
```

It turns out `head_only` was removed in 1.5.0 so updating our code.